// templates.js

export const templatesData = [
  // --- BUSINESS (10 Items) ---
  {
    id: "tpl-bus-1",
    name: "Corporate Summit",
    shortName: "Corporate",
    category: ["business"],
    type: "ready",
    previewUrl: "https://github.com/SuperSimpleDev/ecommerce-project",
    image: "/ai.jpg",
    description: "Professional corporate layout with team hierarchy, history timeline, and investor relations sections.",
    price: "$89",
    priceNote: "Corporate ready",
    tags: ["Investor relations", "Team grids"],
    icons: ["fas fa-building", "fas fa-users"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-bus-2",
    name: "Modern Agency",
    shortName: "Agency X",
    category: ["business", "landing"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/business_2.png",
    description: "Bold typography and dark mode aesthetics for modern digital agencies.",
    price: "$119",
    priceNote: "Premium design",
    tags: ["Dark mode", "Smooth scroll"],
    icons: ["fas fa-moon", "fas fa-mouse"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-bus-3",
    name: "Law Firm Elite",
    shortName: "Legal Pro",
    category: ["business"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/business_3.png",
    description: "Trust-building layout for law firms with case study sections and consultation booking.",
    price: "$99",
    priceNote: "Fast setup",
    tags: ["Case studies", "Booking"],
    icons: ["fas fa-gavel", "fas fa-calendar-check"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-bus-4",
    name: "Construction Co.",
    shortName: "BuildIt",
    category: ["business"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/business_4.png",
    description: "Heavy industry design featuring project galleries and safety certification highlights.",
    price: "$79",
    priceNote: "Industry standard",
    tags: ["Project gallery", "Certifications"],
    icons: ["fas fa-hard-hat", "fas fa-certificate"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-bus-5",
    name: "Tech Startup Hub",
    shortName: "Startup",
    category: ["business", "landing"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/business_5.png",
    description: "Vibrant startup template with roadmap, feature breakdown, and investor deck download.",
    price: "$129",
    priceNote: "Scalable",
    tags: ["Roadmap", "Downloadable assets"],
    icons: ["fas fa-rocket", "fas fa-download"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-bus-6",
    name: "Medical Clinic",
    shortName: "MediCare",
    category: ["business"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/business_6.png",
    description: "Clean, sterile design for clinics with doctor profiles and appointment scheduling.",
    price: "$89",
    priceNote: "HIPAA compliant look",
    tags: ["Doctor profiles", "Scheduling"],
    icons: ["fas fa-stethoscope", "fas fa-notes-medical"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-bus-7",
    name: "Real Estate Prime",
    shortName: "Realty",
    category: ["business"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/business_7.png",
    description: "Property listing focused template with high-res image sliders and virtual tour integration.",
    price: "$149",
    priceNote: "Listing engine",
    tags: ["Virtual tours", "Map integration"],
    icons: ["fas fa-home", "fas fa-map-marked-alt"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-bus-8",
    name: "Consulting Pro",
    shortName: "Consultant",
    category: ["business"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/business_8.png",
    description: "Personal branding for high-ticket consultants. Focus on testimonials and methodology.",
    price: "$79",
    priceNote: "Personal brand",
    tags: ["Testimonials", "Methodology"],
    icons: ["fas fa-user-tie", "fas fa-quote-right"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-bus-9",
    name: "Logistics & Transport",
    shortName: "Logistics",
    category: ["business"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/business_9.png",
    description: "Functional design for transport companies with tracking widgets and fleet details.",
    price: "$85",
    priceNote: "Operational focus",
    tags: ["Tracking widget", "Fleet gallery"],
    icons: ["fas fa-truck", "fas fa-box-open"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-bus-10",
    name: "Co-working Space",
    shortName: "Co-Work",
    category: ["business"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/business_10.png",
    description: "Booking system integration for desks, meeting rooms, and event spaces.",
    price: "$110",
    priceNote: "Booking system",
    tags: ["Room booking", "Events calendar"],
    icons: ["fas fa-building", "fas fa-calendar-alt"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },

  // --- E-COMMERCE (10 Items) ---
  {
    id: "tpl-ecom-1",
    name: "Fashion Boutique",
    shortName: "Chic",
    category: ["ecommerce"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/ecom_1.png",
    description: "Minimalist fashion store with lookbook grids and Instagram feed integration.",
    price: "$129",
    priceNote: "Shopify ready",
    tags: ["Lookbook", "Social feed"],
    icons: ["fas fa-tshirt", "fas fa-hashtag"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-ecom-2",
    name: "Tech Gadgets",
    shortName: "Electro",
    category: ["ecommerce"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/ecom_2.png",
    description: "High-density product grid with comparison tools and spec sheets.",
    price: "$99",
    priceNote: "Conversion focused",
    tags: ["Product compare", "Spec sheets"],
    icons: ["fas fa-microchip", "fas fa-table"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-ecom-3",
    name: "Organic Grocer",
    shortName: "Fresh",
    category: ["ecommerce"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/ecom_3.png",
    description: "Fresh, green layout for local delivery and farm-to-table services.",
    price: "$89",
    priceNote: "Local delivery",
    tags: ["Subscription", "Delivery zones"],
    icons: ["fas fa-leaf", "fas fa-truck-loading"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-ecom-4",
    name: "Handmade Crafts",
    shortName: "Artisan",
    category: ["ecommerce"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/ecom_4.png",
    description: "Story-driven product pages perfect for Etsy sellers moving to their own site.",
    price: "$79",
    priceNote: "Story focused",
    tags: ["Maker story", "Custom orders"],
    icons: ["fas fa-hands", "fas fa-pencil-ruler"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-ecom-5",
    name: "Beauty & Cosmetics",
    shortName: "Glow",
    category: ["ecommerce"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/ecom_5.png",
    description: "Elegant aesthetic with video backgrounds and 'shop the look' features.",
    price: "$139",
    priceNote: "High end",
    tags: ["Video bg", "Shop the look"],
    icons: ["fas fa-magic", "fas fa-video"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-ecom-6",
    name: "Furniture & Decor",
    shortName: "Haus",
    category: ["ecommerce"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/ecom_6.png",
    description: "Wide layout for showcasing interiors and AR-ready product blocks.",
    price: "$109",
    priceNote: "Visual heavy",
    tags: ["Wide layout", "Gallery view"],
    icons: ["fas fa-couch", "fas fa-image"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-ecom-7",
    name: "Digital Downloads",
    shortName: "DigiStore",
    category: ["ecommerce"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/ecom_7.png",
    description: "Optimized for selling eBooks, presets, and software with instant delivery.",
    price: "$69",
    priceNote: "Instant access",
    tags: ["Secure links", "No shipping"],
    icons: ["fas fa-file-download", "fas fa-lock"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-ecom-8",
    name: "Sports & Fitness",
    shortName: "Active",
    category: ["ecommerce"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/ecom_8.png",
    description: "High energy layout with reviews and influencer endorsement sections.",
    price: "$99",
    priceNote: "Brand power",
    tags: ["Reviews", "Influencer blocks"],
    icons: ["fas fa-dumbbell", "fas fa-star"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-ecom-9",
    name: "Pet Supplies",
    shortName: "Paws",
    category: ["ecommerce"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/ecom_9.png",
    description: "Playful and colorful design with breed filtering and care tips blog.",
    price: "$79",
    priceNote: "Fun design",
    tags: ["Breed filter", "Care tips"],
    icons: ["fas fa-paw", "fas fa-filter"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-ecom-10",
    name: "Subscription Box",
    shortName: "SubBox",
    category: ["ecommerce", "landing"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/ecom_10.png",
    description: "Landing page style hybrid for monthly subscription services.",
    price: "$119",
    priceNote: "Recurring revenue",
    tags: ["Step process", "Pricing tiers"],
    icons: ["fas fa-box", "fas fa-sync"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },

  // --- PORTFOLIO (10 Items) ---
  {
    id: "tpl-port-1",
    name: "UX/UI Designer",
    shortName: "UX Pro",
    category: ["portfolio"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/port_1.png",
    description: "Case study focus with interactive prototypes and design thinking process.",
    price: "$69",
    priceNote: "Interactive",
    tags: ["Case studies", "Figma embed"],
    icons: ["fas fa-layer-group", "fas fa-pen-nib"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-port-2",
    name: "Photographer Gallery",
    shortName: "Shutter",
    category: ["portfolio"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/port_2.png",
    description: "Masonry grid gallery with lightbox and client proofing area.",
    price: "$59",
    priceNote: "Image heavy",
    tags: ["Masonry grid", "Client area"],
    icons: ["fas fa-camera", "fas fa-images"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-port-3",
    name: "Developer Resume",
    shortName: "Dev",
    category: ["portfolio"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/port_3.png",
    description: "Terminal-style aesthetics or clean code blocks to showcase GitHub projects.",
    price: "$49",
    priceNote: "Simple setup",
    tags: ["GitHub API", "Dark theme"],
    icons: ["fas fa-code", "fas fa-terminal"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-port-4",
    name: "Architectural Folio",
    shortName: "Arch",
    category: ["portfolio"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/port_4.png",
    description: "Full-screen sliders and minimalist typography to let the structures speak.",
    price: "$89",
    priceNote: "Elegant",
    tags: ["Full slider", "Minimal"],
    icons: ["fas fa-drafting-compass", "fas fa-expand"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-port-5",
    name: "3D Artist Showcase",
    shortName: "Render",
    category: ["portfolio"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/port_5.png",
    description: "WebGL ready template for 3D models and motion graphics.",
    price: "$109",
    priceNote: "Performance heavy",
    tags: ["WebGL support", "Video cover"],
    icons: ["fas fa-cube", "fas fa-film"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-port-6",
    name: "Copywriter Book",
    shortName: "Words",
    category: ["portfolio"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/port_6.png",
    description: "Text-focused layout emphasizing headlines, articles, and ad copy.",
    price: "$55",
    priceNote: "Content first",
    tags: ["Typography", "PDF Viewer"],
    icons: ["fas fa-paragraph", "fas fa-file-pdf"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-port-7",
    name: "Illustrator Grid",
    shortName: "Sketch",
    category: ["portfolio"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/port_7.png",
    description: "Fun, colorful grid layout with shop integration for prints.",
    price: "$65",
    priceNote: "Artist friendly",
    tags: ["Print shop", "Gallery"],
    icons: ["fas fa-paint-brush", "fas fa-store"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-port-8",
    name: "Model / Actor Comp",
    shortName: "Talent",
    category: ["portfolio"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/port_8.png",
    description: "Headshot focused with bio, stats, and downloadable comp card.",
    price: "$59",
    priceNote: "Industry standard",
    tags: ["Comp card", "Reel video"],
    icons: ["fas fa-user", "fas fa-video"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-port-9",
    name: "Student Portfolio",
    shortName: "Grad",
    category: ["portfolio"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/port_9.png",
    description: "Budget-friendly, professional layout for recent graduates.",
    price: "$39",
    priceNote: "Entry level",
    tags: ["Resume link", "About me"],
    icons: ["fas fa-graduation-cap", "fas fa-link"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-port-10",
    name: "Videographer Reel",
    shortName: "Cinema",
    category: ["portfolio"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/port_10.png",
    description: "Cinema-style layout with background video playing immediately.",
    price: "$89",
    priceNote: "Video optimized",
    tags: ["Autoplay", "Vimeo/YT API"],
    icons: ["fas fa-video", "fas fa-play-circle"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },

  // --- BLOG (10 Items) ---
  {
    id: "tpl-blog-1",
    name: "Tech News Daily",
    shortName: "TechNews",
    category: ["blog"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/blog_1.png",
    description: "Magazine style layout with tickers, trending sidebars, and ad spots.",
    price: "$79",
    priceNote: "High content",
    tags: ["Ad ready", "Trending bar"],
    icons: ["fas fa-newspaper", "fas fa-ad"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-blog-2",
    name: "Travel Diaries",
    shortName: "Wander",
    category: ["blog"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/blog_2.png",
    description: "Image-heavy blog with map integration for locations visited.",
    price: "$89",
    priceNote: "Visuals",
    tags: ["Interactive Map", "Photo grid"],
    icons: ["fas fa-plane", "fas fa-map-marker-alt"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-blog-3",
    name: "Foodie Reviews",
    shortName: "Tastemaker",
    category: ["blog"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/blog_3.png",
    description: "Recipe cards support, star ratings, and print-recipe buttons.",
    price: "$69",
    priceNote: "Recipe features",
    tags: ["Recipe card", "Star ratings"],
    icons: ["fas fa-utensils", "fas fa-star"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-blog-4",
    name: "Lifestyle & Wellness",
    shortName: "Balance",
    category: ["blog"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/blog_4.png",
    description: "Soft colors, serif fonts, and podcast player integration.",
    price: "$75",
    priceNote: "Calm design",
    tags: ["Podcast player", "Newsletter"],
    icons: ["fas fa-spa", "fas fa-microphone"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-blog-5",
    name: "Finance & Crypto",
    shortName: "Ledger",
    category: ["blog"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/blog_5.png",
    description: "Data-driven blog with live charts and table widgets.",
    price: "$99",
    priceNote: "Data widgets",
    tags: ["Live charts", "Data tables"],
    icons: ["fas fa-chart-line", "fas fa-coins"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-blog-6",
    name: "Personal Journal",
    shortName: "Diary",
    category: ["blog"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/blog_6.png",
    description: "Simple single-column layout for writers and poets.",
    price: "$49",
    priceNote: "Minimalist",
    tags: ["Readability", "Dark mode"],
    icons: ["fas fa-pen-fancy", "fas fa-book-open"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-blog-7",
    name: "Review Hub",
    shortName: "Reviews",
    category: ["blog"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/blog_7.png",
    description: "Affiliate marketing focused with comparison tables and 'Buy Now' buttons.",
    price: "$109",
    priceNote: "Affiliate ready",
    tags: ["Comparison table", "CTA buttons"],
    icons: ["fas fa-check-double", "fas fa-money-bill-wave"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-blog-8",
    name: "Video Blog / Vlog",
    shortName: "Vlog",
    category: ["blog"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/blog_8.png",
    description: "Video-first feed layout, similar to YouTube but on your own domain.",
    price: "$85",
    priceNote: "Video feed",
    tags: ["Video gallery", "Playlists"],
    icons: ["fas fa-video", "fas fa-play"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-blog-9",
    name: "Academic Journal",
    shortName: "Scholar",
    category: ["blog"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/blog_9.png",
    description: "Formal structure with citations, footnotes, and PDF exports.",
    price: "$95",
    priceNote: "Academic",
    tags: ["Citations", "PDF export"],
    icons: ["fas fa-university", "fas fa-file-alt"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-blog-10",
    name: "Community Forum",
    shortName: "Forum",
    category: ["blog"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/blog_10.png",
    description: "Hybrid blog and discussion board for community engagement.",
    price: "$119",
    priceNote: "Interactive",
    tags: ["Comments", "User profiles"],
    icons: ["fas fa-comments", "fas fa-users"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },

  // --- LANDING PAGES (10 Items) ---
  {
    id: "tpl-land-1",
    name: "Mobile App Launch",
    shortName: "AppLaunch",
    category: ["landing"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/land_1.png",
    description: "Showcase app screens, features, and direct store download links.",
    price: "$69",
    priceNote: "App focused",
    tags: ["Store badges", "Device frames"],
    icons: ["fas fa-mobile-alt", "fab fa-app-store"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-land-2",
    name: "Webinar Registration",
    shortName: "Webinar",
    category: ["landing"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/land_2.png",
    description: "High conversion layout with countdown timer and registration form.",
    price: "$59",
    priceNote: "Event focused",
    tags: ["Countdown", "Lead form"],
    icons: ["fas fa-clock", "fas fa-user-plus"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-land-3",
    name: "SaaS Free Trial",
    shortName: "SaaS Trial",
    category: ["landing", "business"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/land_3.png",
    description: "Comparison of Free vs Pro plans to drive trial signups.",
    price: "$99",
    priceNote: "Conversion",
    tags: ["Pricing table", "Trial CTA"],
    icons: ["fas fa-cloud", "fas fa-check"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-land-4",
    name: "E-book Lead Magnet",
    shortName: "E-book",
    category: ["landing"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/land_4.png",
    description: "Simple page to trade an email address for a downloadable PDF.",
    price: "$49",
    priceNote: "Lead gen",
    tags: ["Email capture", "Mockup"],
    icons: ["fas fa-book", "fas fa-envelope"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-land-5",
    name: "Course Pre-sale",
    shortName: "Pre-sale",
    category: ["landing"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/land_5.png",
    description: "Long-form sales letter design with curriculum breakdown.",
    price: "$119",
    priceNote: "Sales copy",
    tags: ["Curriculum", "Bonuses"],
    icons: ["fas fa-list-ol", "fas fa-gift"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-land-6",
    name: "Coming Soon",
    shortName: "Soon",
    category: ["landing"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/land_6.png",
    description: "Placeholder page with 'Notify Me' feature for pre-launch buzz.",
    price: "$39",
    priceNote: "Temporary",
    tags: ["Notify form", "Social links"],
    icons: ["fas fa-bell", "fas fa-share-alt"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-land-7",
    name: "Event / Conference",
    shortName: "Summit",
    category: ["landing"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/land_7.png",
    description: "Speaker lineup, schedule, and ticket purchasing integration.",
    price: "$129",
    priceNote: "Event full",
    tags: ["Schedule", "Ticketing"],
    icons: ["fas fa-microphone-alt", "fas fa-ticket-alt"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-land-8",
    name: "NFT Drop",
    shortName: "NFT",
    category: ["landing"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/land_8.png",
    description: "Cyberpunk aesthetic for Web3 projects and roadmap reveal.",
    price: "$149",
    priceNote: "Web3 ready",
    tags: ["Roadmap", "Discord link"],
    icons: ["fas fa-cube", "fab fa-discord"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
  {
    id: "tpl-land-9",
    name: "Newsletter Signup",
    shortName: "Substack",
    category: ["landing"],
    type: "ready",
    previewUrl: "#",
    image: "img/templates/land_9.png",
    description: "Minimalist page focused solely on growing a newsletter audience.",
    price: "$45",
    priceNote: "Growth",
    tags: ["Archive view", "Signup"],
    icons: ["fas fa-envelope-open", "fas fa-rss"],
    badge: "Ready-Made",
    badgeClass: "wc-template-tag--ready"
  },
  {
    id: "tpl-land-10",
    name: "Product Prototype",
    shortName: "Beta",
    category: ["landing"],
    type: "custom",
    previewUrl: "#",
    image: "img/templates/land_10.png",
    description: "For physical products in development, gathering feedback and testers.",
    price: "$89",
    priceNote: "Feedback",
    tags: ["Survey", "Video demo"],
    icons: ["fas fa-flask", "fas fa-comment-dots"],
    badge: "Customizable",
    badgeClass: "wc-template-tag--custom"
  },
];